export {VERTICES_IN_TRIANGLE, POSITION_BUFFER_SIZE, COLOR_BUFFER_SIZE, BACKGROUND_COLOR}

const VERTICES_IN_TRIANGLE = 3;
const POSITION_BUFFER_SIZE = 8;
const COLOR_BUFFER_SIZE = 16;


// CONFIGURABLE
const BACKGROUND_COLOR = [0.8, 0.8, 0.8, 1.0];
